#!/usr/bin/env python3
"""Convert .mlir template files into a C++ include file with raw string literals.

Usage:
    python tools/embed_templates.py aten/src/ATen/pyre/dispatch/templates/*.mlir \
        -o aten/src/ATen/pyre/dispatch/PyreKernelTemplates.inc

Each .mlir file becomes a `static constexpr const char kTemplate_<name>[]`
variable containing the file contents as a raw string literal. The variable
name is derived from the filename (e.g., elementwise_binary.mlir →
kTemplate_elementwise_binary).

Templates remain human-editable .mlir files during development. This script
runs at build time to embed them into C++ — no loose resource files at
distribution time.
"""

import argparse
import hashlib
import os
import sys
from pathlib import Path


def sanitize_name(filename: str) -> str:
    """Convert a filename to a valid C++ identifier."""
    stem = Path(filename).stem
    return stem.replace("-", "_").replace(".", "_")


def generate_inc(template_paths: list[str], output_path: str) -> None:
    with open(output_path, "w") as out:
        out.write("// Auto-generated by tools/embed_templates.py — do not edit.\n")
        out.write("#pragma once\n\n")
        out.write("namespace at::pyre {\n\n")

        for path in sorted(template_paths):
            name = sanitize_name(os.path.basename(path))
            with open(path) as f:
                content = f.read()

            digest = hashlib.sha1(content.encode()).hexdigest()

            out.write(
                f'static constexpr const char kTemplate_{name}[] = R"mlir(\n'
            )
            out.write(content)
            if not content.endswith("\n"):
                out.write("\n")
            out.write(')mlir";\n')
            out.write(
                f'static constexpr const char kTemplate_{name}_sha1[] = "{digest}";\n\n'
            )

        out.write("} // namespace at::pyre\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Embed .mlir templates into C++ raw string literals."
    )
    parser.add_argument("templates", nargs="+", help=".mlir template files")
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="Output .inc file path",
    )
    args = parser.parse_args()

    missing = [p for p in args.templates if not os.path.isfile(p)]
    if missing:
        print(f"Error: template files not found: {missing}", file=sys.stderr)
        sys.exit(1)

    generate_inc(args.templates, args.output)
    print(f"Generated {args.output} from {len(args.templates)} template(s)")


if __name__ == "__main__":
    main()
